# Generated by Django 5.2.8 on 2026-02-08 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_membershipcategory'),
        ('users', '0003_user_blood_group_user_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.membershipcategory'),
        ),
    ]
