# Generated by Django 5.2.8 on 2026-02-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_membership_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
