# Generated by Django 5.2.8 on 2026-02-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_banner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='banners/thumbnails/'),
        ),
    ]
