# Generated by Django 5.2.8 on 2026-02-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_membershipcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipcategory',
            name='vote',
            field=models.BooleanField(default=True),
        ),
    ]
