# Generated by Django 5.2.8 on 2026-02-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_membershipcategory_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='vote',
            field=models.BooleanField(default=False),
        ),
    ]
