# Generated by Django on 2026-02-16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_gallery"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=100, null=True, blank=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="study-center/")),
                (
                    "thumbnail",
                    models.ImageField(
                        upload_to="study-center/thumbnails/", blank=True, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
