# Generated by assistant to merge concurrent migrations 0014_album and 0014_videomedia

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_album"),
        ("core", "0014_videomedia"),
    ]

    operations = []
