# Generated by Django 5.2.8 on 2026-02-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
