# Generated by Django 5.2.8 on 2026-02-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_events_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='organizer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
