# Generated by Django 5.2.8 on 2026-02-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_events_organizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('total_members', models.PositiveIntegerField(default=0)),
                ('life_members', models.PositiveIntegerField(default=0)),
                ('professional_members', models.PositiveIntegerField(default=0)),
                ('student_members', models.PositiveIntegerField(default=0)),
                ('general_members', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
